# Generated by Django 5.2.1 on 2025-06-09 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversationmessage",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="conversationthread",
            options={"ordering": ["-updated_at"]},
        ),
    ]
