# Generated by Django 5.2.1 on 2025-06-06 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=200)),
                ("account_name", models.CharField(max_length=200)),
                ("account_category", models.CharField(max_length=100)),
                (
                    "account_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=19),
                ),
                ("currency", models.CharField(max_length=20)),
                ("account_restricted", models.BooleanField(default=False)),
                ("extra_t24_data", models.TextField(default="{}")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
