# Generated by Django 5.2.1 on 2025-06-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_balance",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=19
            ),
        ),
    ]
