# Generated by Django 5.2.1 on 2025-06-07 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cbs", "0003_alter_bankaccount_options_bankaccount_default"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("Transfer", "Transfer"),
                            ("Payment", "Payment"),
                            ("Deposit", "Deposit"),
                            ("Withdrawal", "Withdrawal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "credit_debit_status",
                    models.CharField(
                        blank=True,
                        choices=[("Debit", "Debit"), ("Credit", "Credit")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("obj_date", models.DateTimeField(auto_now_add=True)),
                (
                    "history_ct",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_account", models.CharField(max_length=100)),
                (
                    "recipient_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "recipient_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "recipient_iban_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "recipient_bank",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "recipient_swift_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "recipient_phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "recipient_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "recipient_residence_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "charges",
                    models.CharField(
                        choices=[("SELF", "Self"), ("BENEFICIARY", "Beneficiary")],
                        default="SELF",
                        max_length=50,
                    ),
                ),
                ("network", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("Own Account Transfer", "Own Account Transfer"),
                            ("Same Bank Transfer", "Same Bank Transfer"),
                            ("Other Bank Transfer", "Other Bank Transfer"),
                            ("International Transfer", "International Transfer"),
                            ("Account To Wallet", "Account To Wallet"),
                        ],
                        max_length=50,
                    ),
                ),
                ("purpose_of_transaction", models.CharField(max_length=240)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Success", "Success"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("failed_reason", models.TextField(blank=True, null=True)),
                ("edited", models.BooleanField(default=False)),
                ("reference", models.CharField(blank=True, max_length=400, null=True)),
                ("channel", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "t24_reference",
                    models.CharField(blank=True, max_length=240, null=True),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, null=True, unique=True
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "source_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="cbs.bankaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
    ]
