# Generated by Django 5.2.1 on 2025-06-07 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbs", "0007_bankstatement"),
        ("datatable", "0004_telcodataplan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beneficiary_type",
                    models.CharField(
                        choices=[
                            ("Airtime", "Airtme"),
                            ("Data", "Data"),
                            ("Same Bank", "Same Bank"),
                            ("Other Bank", "Other Bank"),
                            ("Account To Wallet", "Account To Wallet"),
                            ("International Transfer", "International Transfer"),
                            ("Bill Payment", "Bill Paymnet"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "avatar",
                    models.FileField(
                        blank=True, null=True, upload_to="beneficiary_avatars/"
                    ),
                ),
                ("beneficiary_number", models.CharField(max_length=200)),
                ("beneficiary_name", models.CharField(max_length=200)),
                ("benficiary_nick_name", models.CharField(max_length=200)),
                (
                    "beneficiary_country",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "beneficiary_swift_code",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "beneficiary_bank",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "beneficiary_bank_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "beneficiary_iban_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "beneficiary_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "beneficiary_residence_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, null=True, unique=True
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "biller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beneficiaries",
                        to="cbs.paymentbiller",
                    ),
                ),
                (
                    "network_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beneficiaries",
                        to="datatable.networkprovider",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beneficiaries",
                        to="cbs.bankaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beneficiaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="ChequeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cheque_request_type",
                    models.CharField(
                        choices=[
                            ("CHEQUE REQUEST", "Cheque Request"),
                            ("BLOCK CHEQUE", "Block Cheque Request"),
                            ("CONFIRM CHEQUE", "Cheque Confirmation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "leaves",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("10 LEAVES", "Ten"),
                            ("25 LEAVES", "Twenty Five"),
                            ("50 LEAVES", "Fifty"),
                            ("75 LEAVES", "Seventy Five"),
                            ("100 LEAVES", "Hundred"),
                            ("150 LEAVES", "One Fifty"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("cheque_numbers", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                ("cheque_date", models.DateField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=200, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cheque_services_requests",
                        to="datatable.bankbranch",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cheque_requests",
                        to="cbs.bankaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_cheque_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="StandingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "standing_order_type",
                    models.CharField(
                        choices=[
                            ("Airtime", "Own Account Transfer"),
                            ("Same Bank", "Same Bank"),
                            ("Other Bank", "Other Bank"),
                            ("Account To Wallet", "Account To Wallet"),
                            ("Bill Payment", "Bill Paymnet"),
                        ],
                        max_length=100,
                    ),
                ),
                ("recipient_account", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=19)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("purpose_of_transaction", models.CharField(max_length=200)),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Yearly", "Yearly"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "cbs_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Requested", "Requested"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=100,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, null=True, unique=True
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "network_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="standing_orders",
                        to="datatable.networkprovider",
                    ),
                ),
                (
                    "other_bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="standing_orders",
                        to="datatable.otherbank",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="standing_order",
                        to="cbs.bankaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="standing_order",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
    ]
