# Generated by Django 5.2.1 on 2025-06-08 00:28

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cbs", "0009_loancategory_loanrequest_laonrequestfile"),
        ("datatable", "0004_telcodataplan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CASH DEPOSIT", "Cash Deposit"),
                            ("CASH WITHDRAWAL", "Cash Withdrawal"),
                            ("CHEQUE DEPOSIT", "Cheque Deposit"),
                            ("CHEQUE WITHDRAWAL", "Cheque Withdrawal"),
                            ("ENQUIRY", "Enquiry"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "source_account",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "source_account_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cheque_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "name_of_cheque_issuer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[("SELF", "Self"), ("THIRD PARTY", "Third Party")],
                        max_length=20,
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("id_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="UPCOMING",
                        max_length=100,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, null=True, unique=True
                    ),
                ),
                (
                    "booking_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_bookings",
                        to="datatable.bankbranch",
                    ),
                ),
                (
                    "issuing_bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cheque_bookings",
                        to="datatable.otherbank",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="CardlessWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        blank=True,
                        choices=[("ATM", "Atm"), ("MERCHANT", "Merchant")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=19)),
                ("valid_through", models.DateField()),
                (
                    "withdrawal_party",
                    models.CharField(
                        blank=True,
                        choices=[("SELF", "Self"), ("THIRD_PARTY", "Third Party")],
                        default="SELF",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "recipient_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("token_redeemed", models.BooleanField(default=False)),
                ("token_expired", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, null=True, unique=True
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cardless_withdrawals",
                        to="cbs.bankaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cardless_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="EmailIndemnity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_email", models.EmailField(max_length=254)),
                (
                    "secondary_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("airtime", models.BooleanField(default=False)),
                ("data", models.BooleanField(default=False)),
                ("bill_payment", models.BooleanField(default=False)),
                ("international_transfer", models.BooleanField(default=False)),
                ("account_to_wallet", models.BooleanField(default=False)),
                ("other_bank_transfer", models.BooleanField(default=False)),
                ("same_bank_transfer", models.BooleanField(default=False)),
                ("own_account_transfer", models.BooleanField(default=False)),
                ("merchant_payment", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, null=True, unique=True
                    ),
                ),
                (
                    "source_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_indemnity",
                        to="cbs.bankaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_indemnity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="ExpenseLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "limit_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Account Budget", "Account Budget"),
                            ("Categorical Budget", "Categorical Budget"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("limit_amount", models.DecimalField(decimal_places=2, max_digits=19)),
                (
                    "amount_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=19),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=100,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, null=True, unique=True
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_limits",
                        to="cbs.bankaccount",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="datatable.transactionpurpose",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_limits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
    ]
