# Generated by Django 5.2.1 on 2025-06-08 04:32

import creditcards.models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cbs", "0011_billsharing_billsharingpyee"),
        ("datatable", "0004_telcodataplan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_scheme",
                    models.CharField(
                        choices=[("VISA", "Visa"), ("MASTERCARD", "Mastercard")],
                        default="VISA",
                        max_length=50,
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        blank=True,
                        choices=[("DEBIT CARD", "Debit"), ("CREDIT CARD", "Credit")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "card_form",
                    models.CharField(
                        choices=[
                            ("PHYSICAL CARD", "Physical"),
                            ("VIRTUAL CARD", "Virtual"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "card_number",
                    creditcards.models.CardNumberField(
                        max_length=25, verbose_name="card number"
                    ),
                ),
                (
                    "card_expiry",
                    creditcards.models.CardExpiryField(verbose_name="expiration date"),
                ),
                (
                    "card_code",
                    creditcards.models.SecurityCodeField(
                        max_length=4, verbose_name="security code"
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "virtual_card_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GIFT CARD", "Gift Card"),
                            ("SHOPPING CARD", "Shopping Card"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "card_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("BLOCKED", "Blocked"),
                            ("FROZEN", "Frozen"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=50,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, null=True, unique=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="CardManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "management_type",
                    models.CharField(
                        choices=[
                            ("RENEW CARD", "Renew Card"),
                            ("REPLACE CARD", "Replace Card"),
                            ("BLOCK CARD", "Block Card"),
                            ("FREEZE CARD", "Freeze Card"),
                            ("UNFREEZE CARD", "Unfreeze Card"),
                        ],
                        max_length=100,
                    ),
                ),
                ("reason", models.TextField()),
                ("through_date", models.DateField(blank=True, null=True)),
                (
                    "delivery_method",
                    models.CharField(
                        blank=True,
                        choices=[("Branch PickUp", "Branch Pickup")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, null=True, unique=True
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_managements",
                        to="cbs.card",
                    ),
                ),
                (
                    "pick_up_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_management",
                        to="datatable.bankbranch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_managements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="CardRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[("DEBIT CARD", "Debit"), ("CREDIT CARD", "Credit")],
                        max_length=100,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("Branch PickUp", "Branch Pickup")], max_length=100
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, null=True, unique=True
                    ),
                ),
                (
                    "pick_up_branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_requests",
                        to="datatable.bankbranch",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_requests",
                        to="cbs.bankaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="TravelNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_date", models.DateField()),
                ("return_date", models.DateField()),
                ("destination_country", models.CharField(max_length=100)),
                (
                    "alternative_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, null=True, unique=True
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="travel_notices",
                        to="cbs.card",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_notices",
                        to="cbs.bankaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="travel_notice",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
    ]
