# Generated by Django 5.2.1 on 2025-06-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbs", "0012_card_cardmanagement_cardrequest_travelnotice"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="virtual_card_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=19, null=True
            ),
        ),
    ]
