# Generated by Django 5.2.1 on 2025-06-09 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbs", "0014_complaintcategory_complaint_complaintfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankCharges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("Own Account Transfer", "Own Account Transfer"),
                            ("Same Bank Transfer", "Same Bank Transfer"),
                            ("Other Bank Transfer", "Other Bank Transfer"),
                            ("International Transfer", "International Transfer"),
                            ("Account To Wallet", "Account To Wallet"),
                            ("Airtime", "Airtime"),
                            ("Data", "Data"),
                            ("Bill Payment", "Bill Payment"),
                            ("Card Requests", "Card Reqeusts"),
                            ("Cheque Requests", "Cheque Requests"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "flat_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, null=True, unique=True
                    ),
                ),
            ],
        ),
    ]
