# Generated by Django 5.2.1 on 2025-06-06 00:42

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("Current Local", "Current Local"),
                            ("Current Joint", "Current Joint"),
                            ("Current Com", "Current Com"),
                            ("Current FCA", "Current Fca"),
                            ("Current FEA", "Current Fea"),
                            ("Savings Local", "Savings Local"),
                        ],
                        max_length=240,
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                ("category", models.CharField(max_length=20)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_udpated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Atm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(default="São Tomé and Príncipe", max_length=240),
                ),
                (
                    "langtitude_cordinates",
                    models.CharField(blank=True, max_length=240, null=True),
                ),
                (
                    "longitude_cordinates",
                    models.CharField(blank=True, max_length=240, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=400, null=True)),
                ("closed", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_udpated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="BankBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                (
                    "country",
                    models.CharField(default="São Tomé and Príncipe", max_length=240),
                ),
                (
                    "langtitude_cordinates",
                    models.CharField(blank=True, max_length=240, null=True),
                ),
                (
                    "longitude_cordinates",
                    models.CharField(blank=True, max_length=240, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=400, null=True)),
                ("closed", models.BooleanField(default=False)),
                (
                    "secrets",
                    models.UUIDField(blank=True, default=uuid.uuid4, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_udpated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CardServiceReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_udpated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FileManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                ("file", models.FileField(upload_to="file_management/")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_udpated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="IDType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_udpated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="NotificationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            (
                                "ACCOUNT_PHONE_NUMBER_VERIFICATION",
                                "Account Phone Number Verification",
                            ),
                            ("EMAIL_TOKEN_VERIFICATION", "Email Token Verification"),
                            (
                                "COPORATE_STAFF_ACCOUNT_DETAILS",
                                "Coporate Staff Account Details",
                            ),
                            ("PASSWORD_OTP_RESET", "Password Otp Reset"),
                            ("TEMPORARY_PASSWORD", "Temporary Password"),
                            ("PASSWORD_RESET_LINK", "Password Reset Link"),
                            ("SEND_OTP", "Send Otp"),
                            ("PIN_RESET_LINK", "Pin Reset Link"),
                            (
                                "CORPORATE_AC_TEMP_PASSWORD",
                                "Corporate Ac Temp Password",
                            ),
                            ("CORPORATE_AC_ISSUED", "Corporate Ac Issued"),
                            ("CORPORATE_AC_REJECTED", "Corporate Ac Rejected"),
                            ("TRANSFER APPROVED", "Transfer Approved"),
                            ("TRANSFER REJECTED", "Transfer Rejected"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=240, null=True)),
                ("message", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_udpated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_udpated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("date_created",),
            },
        ),
        migrations.CreateModel(
            name="OtherBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_udpated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SecurityQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_udpated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SwiftCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("swift_code", models.CharField(max_length=50, unique=True)),
                ("bank_name", models.CharField(max_length=100)),
                ("bank_address", models.CharField(max_length=200)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_udpated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TermsAndCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile_terms_and_conditions",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "account_opening_terms_and_conditions",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_udpated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionPurpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_udpated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DigitalPlatformVisits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
