# Generated by Django 5.2.1 on 2025-06-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datatable", "0002_networkprovider"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networkprovider",
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="networkprovider",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="networkprovider",
            name="country",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="networkprovider",
            name="currency",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="otherbank",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="otherbank",
            name="code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="otherbank",
            name="country",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="otherbank",
            name="currency",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="networkprovider",
            name="name",
            field=models.CharField(max_length=240),
        ),
    ]
