# Generated by Django 5.2.1 on 2025-06-07 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "datatable",
            "0003_alter_networkprovider_options_networkprovider_code_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TelcoDataPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=240)),
                ("data", models.CharField(max_length=240)),
                ("price", models.DecimalField(decimal_places=2, max_digits=19)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_udpated", models.DateTimeField(auto_now=True)),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_plans",
                        to="datatable.networkprovider",
                    ),
                ),
            ],
        ),
    ]
