# Generated by Django 5.2.1 on 2025-06-08 10:05

import django.db.models.deletion
import ocr.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", ocr.models.IdCardField(default=dict)),
                (
                    "middle_name",
                    ocr.models.IdCardField(blank=True, default=dict, null=True),
                ),
                ("last_name", ocr.models.IdCardField(default=dict)),
                ("date_of_birth", ocr.models.IdCardField(default=dict)),
                ("gender", ocr.models.IdCardField(default=dict)),
                (
                    "id_number",
                    ocr.models.IdCardField(blank=True, default=dict, null=True),
                ),
                ("document_number", ocr.models.IdCardField(default=dict)),
                ("date_of_issue", ocr.models.IdCardField(default=dict)),
                ("date_of_expiry", ocr.models.IdCardField(default=dict)),
                ("country", ocr.models.IdCardField(default=dict)),
                ("state", ocr.models.IdCardField(blank=True, default=dict, null=True)),
                (
                    "nationality",
                    ocr.models.IdCardField(blank=True, default=dict, null=True),
                ),
                ("mrz", ocr.models.IdCardField(blank=True, default=dict, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("passport", "Passport"),
                            ("national_id", "National ID"),
                            ("driver_license", "Driver License"),
                        ],
                        max_length=20,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("is_confirmed", models.BooleanField(default=False)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("review", "Needs Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_score", models.IntegerField(default=0)),
                ("reject_score", models.IntegerField(default=0)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                (
                    "additional_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional image URLs/paths stored as JSON array",
                    ),
                ),
                (
                    "id_number_text",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "document_number_text",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_card",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "id_cards",
                "indexes": [
                    models.Index(
                        fields=["user", "document_type"],
                        name="id_cards_user_id_2a0892_idx",
                    ),
                    models.Index(
                        fields=["decision", "created_at"],
                        name="id_cards_decisio_4a621a_idx",
                    ),
                    models.Index(
                        fields=["id_number_text"], name="id_cards_id_numb_21ff6b_idx"
                    ),
                    models.Index(
                        fields=["document_number_text"],
                        name="id_cards_documen_f92a54_idx",
                    ),
                    models.Index(
                        fields=["verified", "is_confirmed"],
                        name="id_cards_verifie_39167f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OnboardingStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("document_upload", "Document Upload"),
                            ("id_verification", "ID Verification"),
                            ("id_confirmation", "ID Confirmation"),
                            ("liveness_check", "Liveness Check"),
                            ("completed", "Completed"),
                        ],
                        default="document_upload",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_stage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_stages",
                "indexes": [
                    models.Index(
                        fields=["user", "stage"], name="onboarding__user_id_fc018b_idx"
                    ),
                    models.Index(
                        fields=["stage", "updated_at"],
                        name="onboarding__stage_5f3959_idx",
                    ),
                ],
            },
        ),
    ]
