# Generated by Django 5.2.1 on 2025-06-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idcard",
            name="back_image",
            field=models.ImageField(
                blank=True,
                help_text="Back side of the ID document",
                null=True,
                upload_to="id_cards/back",
            ),
        ),
        migrations.AddField(
            model_name="idcard",
            name="front_image",
            field=models.ImageField(
                blank=True,
                help_text="Front side of the ID document",
                null=True,
                upload_to="id_cards/front",
            ),
        ),
        migrations.AddField(
            model_name="idcard",
            name="self_image",
            field=models.ImageField(
                blank=True,
                help_text="Selfie with the ID document",
                null=True,
                upload_to="id_cards/self",
            ),
        ),
        migrations.AddField(
            model_name="idcard",
            name="selfie_video",
            field=models.FileField(
                blank=True,
                help_text="Selfie video for verification",
                null=True,
                upload_to="id_cards/selfie_video",
            ),
        ),
    ]
