# Generated by Django 5.2.1 on 2025-06-09 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocr", "0002_idcard_back_image_idcard_front_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="idcard",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email address for temporary storage before user creation",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="idcard",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_card",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="idcard",
            index=models.Index(fields=["email"], name="id_cards_email_71b8b3_idx"),
        ),
    ]
