# Generated by Django 5.2.1 on 2025-06-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocr", "0003_idcard_email_alter_idcard_user_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="idcard",
            name="id_cards_email_71b8b3_idx",
        ),
        migrations.AlterField(
            model_name="idcard",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
