# Generated by Django 5.2.1 on 2025-06-10 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0004_remove_idcard_id_cards_email_71b8b3_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="idcard",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_card",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
